//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Danilov_library
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public string isbn { get; set; }
        public string author { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> publish_year { get; set; }
        public Nullable<int> genre_id { get; set; }
        public int ID { get; set; }
    }
}
