//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Danilov_library
{
    using System;
    using System.Collections.Generic;
    
    public partial class books_reserved
    {
        public int ID { get; set; }
        public string book_id { get; set; }
        public string student_id { get; set; }
        public System.DateTime reserv_ends { get; set; }
        public bool taken { get; set; }
    }
}
