//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Danilov_library
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public string lib_card_number { get; set; }
        public string stud_card_number { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
    }
}
